### ISSUE TITLE
text does not wrap around image 

### ISSUE THREAD

**Issue by ruthkonyn** [jones58/fare-free-london#1]
on the 'Aims' page there is text to the left of an image at the top of the page. The rest of the text is only displayed in the left hand column. It would enhance a great page to have the text spread across the page underneath the image - thus needing less scrolling - and showing less white space. I'm using firefox on ubuntu linux. 
![Uploading image.png…]()

**Comment by jackkershaw** [comment]
thanks for the advice, I've fixed this now by making the text centred on desktop.
